development:
  adapter: postgresql
  host: localhost
  database: quiz
  username: postgres
  password: 'password'

production:
  adapter: postgresql
  host: localhost
  database: prodquiz
  username: postgres
  password: 'password'
